name: pkgcheck

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["pkgdown"]
    types: [completed]
    branches: [main, master]
  workflow_dispatch:

jobs:
  pkgcheck:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
        with:
          post-to-issue: false
